import type { Metadata } from "next";
import "../styles/globals.scss";
import ReactQueryProvider from "./provider";

export const metadata: Metadata = {
  title: "MKS Sistemas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <ReactQueryProvider>
          <div>{children}</div>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
